project:
  type: website
  output-dir: docs
  resources:
      - "*.xlsx"

website:
  title: "Quality Questions"
  sidebar:
    style: docked
    contents:
      - text: "Introduction"
        href: index.qmd
      - text: "Quality Questions"
        href: quality_questions.qmd
      - text: "FAQs"
        href: faqs.qmd
      - text: "Feedback"
        href: feedback.qmd
      - text: "Get the assumptions and decision log template"
        href: "assumptions_and_decision_log_template.xlsx"
      - text: "Assumptions log guide"
        href: assumptions_log.qmd
      - text: "Issues log guide"
        href: issues_log.qmd
      - text: "Sample assumptions log"
        href: sample_assumptions_log.qmd
      - text: "Get the commissioning log template"
        href: "commissioning_template.xlsx"

format:
  html:
    page-layout: full
    theme: cosmo
    toc: true
    embed-resources: true
    
